### ISSUE TITLE
Vue 2 / Nuxt 2 notes

### ISSUE THREAD

**Issue by galaxyblur** [OvidijusParsiunas/active-table#1]
Thanks for a great component! Surprisingly, one of the few out there that is actively being worked on.

A few notes about how I got this working in Vue 2 (you don't mention Vue version in your docs, but your sandbox example uses Vue 3, so maybe this is unique to Vue 2 or Nuxt 2):

- I have to `JSON.stringify(content)` myself before passing it to `<active-table>` as a prop, otherwise Vue will do its own serialization which is NOT JSON.
- The same is true for object-based props like `columnDropdown`
- My eslint rules require hyphenated prop names, which I think is fairly common. I wrapped `<active-table>` with `<!-- eslint-disable vue/html-self-closing vue/attribute-hyphenation -->` (and `enable` after) to silence these errors.

**Comment by OvidijusParsiunas** [comment]
Hey @galaxyblur! Thankyou so much for using ActiveTable!

### Passing object/arrays into ActiveTable in Vue 2
To prevent the internal property processors in Vue2 from changing the passed values, we can explicitly assert the data binding to be regarded as a property by adding the [.prop](https://v2.vuejs.org/v2/api/#v-bind) modifier:

When component data is set as follows:
```
data() {
    return {
      content: [
        ["Planet", "Diameter"],
        ["Earth", 12756],
      ]}},
```
You can pass it like this:
```
<active-table :content.prop="content"/>
```

Or you can alternatively pass data directly into the component as follows:
```
<active-table :content.prop="[['Planet', 'Diameter'],['Earth', 12756]]"/>
```

I have created a new Code Sandbox for this ([link](https://codesandbox.io/s/active-table-vue2-32f04e?file=/src/App.vue)) and will be adding it to the [Examples](https://activetable.io/docs/examples) page shortly.

### Hyphen case in ActiveTable
The above solution should automatically take care of this (for **Vue2**). So you can change ```:headerIconStyle.prop``` to ```:header-icon-style.prop``` and it should work.

For anyone using **Vue3** - you need to add the [.camel](https://v2.vuejs.org/v2/api/#v-bind) modifier to the property instead - so change ```:headerIconStyle``` to ```:header-icon-style.camel```.

(If anyone has a hyphen case solution for the framework they are using - please add it as a comment in this thread)

As a **fallback** solution for **every framework**, if you cannot use camelCase, you can always stringify your value and set it on the component as an _attribute_ and not a _property_, this will allow you to lower case all of the attribute name's letters:

Change ```headerStyles='{"default":{"backgroundColor":"#d6d6d630"}}'``` to  ```headerstyles='{"default":{"backgroundColor":"#d6d6d630"}}'```.

For reference attributes similar to properties - but they are passed into the element in the markup (html) (with no additional framework syntax) and always require the value to be in a string form. See this [thread](https://stackoverflow.com/questions/6003819/what-is-the-difference-between-properties-and-attributes-in-html) for more information.

**Comment by OvidijusParsiunas** [comment]
Just to note, ActiveTable is still in development and will have its official release later this month. I am very surprised + excited that people have found this component and are already using it! :tada:

I am currently working on a few open source projects and am planning to release them in a sequence (so I could then fully focus on maintaining them rather than developing something new), all of which should be completed this month (if it goes to plan ofcourse).

There will be updates actively coming into this repo as I am polishing up the website, but the component library should be fully usable.

Nevertheless, if you notice any issues, have suggestions for improvements or certain things in the API just don't make sense - please create issue tickets and I will certainly try to address them! This component is very fresh, hence it is best to get anything out of the way now before the wider community will start using it. :rocket:

Thankyou once again @galaxyblur!

**Comment by galaxyblur** [comment]
@OvidijusParsiunas thank you so much for the advice! Everything worked as you described. Here is my final code in case it helps anyone else understand. This is for displaying a simpler table with non-editable data.

```
      <active-table
        :content.prop="tableData"
        :is-cell-text-editable.prop="false"
        :is-header-text-editable.prop="false"
        :display-header-icons.prop="false"
        :display-add-new-row.prop="false"
        :display-add-new-column.prop="false"
        :display-index-column.prop="false"
        :striped-rows.prop="true"
        :column-dropdown.prop="tableColDropdown"
        :row-dropdown.prop="tableRowDropdown"
        :overflow.prop="{ maxWidth: '100%' }"
        :table-style.prop="{ width: '100%' }"
        :header-styles.prop="{ default: { 'white-space': 'nowrap', 'text-overflow': 'ellipsis', overflow: 'hidden' } }"
        :style="{ width: '100%' }"
      ></active-table>

// ...

      tableColDropdown: {
        isSortAvailable: true,
        isDeleteAvailable: false,
        isInsertLeftAvailable: false,
        isInsertRightAvailable: false,
        isMoveAvailable: false,
      },
      tableRowDropdown: {
        displaySettings: {
          isAvailable: false,
        },
      },

```

**Comment by OvidijusParsiunas** [comment]
Please note that the properties used for the configuration of the example above adhere to active-table version that is earlier than 0.1.0 which may differ to the latest version of the component. Please check the [documentation](https://activetable.io/docs/table) to make sure you are using the correct properties or directly refer to our [examples](https://activetable.io/examples/design).
