### ISSUE TITLE
Documentation example code doesn't work in Svelte and Vue

### ISSUE THREAD

**Issue by djamez** [OvidijusParsiunas/active-table#15]
Adding `tableStyle` appears to break in both Svelte and Vue. Svelte example below:

```diff
<main>
   <h1>Active Table:</h1>
  <active-table
    displayAddNewColumn = false
    displayAddNewRow=false
    content={content}
    frameComponentsStyles={JSON.stringify(frameComponentsStyles)}
    headerStyles={'{"default":{"backgroundColor": "#d6d6d630"}}'}
+    tableStyle='{
+      "borderRadius": "10px",
+      "boxShadow": "rgb(172 172 172 / 17%) 0px 0.5px 1px 0px",
+      "width":"100%"
+    }'
  />
</main>```

**Comment by OvidijusParsiunas** [comment]
Hi @djamez. In Svelte, it appears that Svelte and Vue do not recognise the Lit Element's (framework used to make Active Table) properties as attributes (syntax you are using for tableStyle) and instead immediately interprets them as actual properties.
Because of this you can't use the simple tableStyle='{"borderRadius": "10px"}' syntax and instead you need to change it to how the `headerStyles` property is used:

**Svelte** (using a backtick ` to allow a multi-line string):
```
tableStyle={`{
    "borderRadius": "10px",
    "boxShadow": "rgb(172 172 172 / 17%) 0px 0.5px 1px 0px",
    "width":"100%"
}`}
```

**Vue**:

```
:tableStyle="{
      borderRadius: '10px',
      boxShadow: 'rgb(172 172 172 / 17%) 0px 0.5px 1px 0px',
      width: '100%',
    }"
```

Let me know if this helps you.

**Comment by djamez** [comment]
> Hi @djamez. In Svelte, it appears that Svelte and Vue do not recognise the Lit Element's (framework used to make Active Table) properties as attributes (syntax you are using for tableStyle) and instead immediately interprets them as actual properties. Because of this you can't use the simple tableStyle='{"borderRadius": "10px"}' syntax and instead you need to change it to how the `headerStyles` property is used:
> 
> **Svelte** (using a backtick ` to allow a multi-line string):
> 
> ```
> tableStyle={`{
>     "borderRadius": "10px",
>     "boxShadow": "rgb(172 172 172 / 17%) 0px 0.5px 1px 0px",
>     "width":"100%"
> }`}
> ```
> 
> **Vue**:
> 
> ```
> :tableStyle="{
>     borderRadius: '10px',
>     boxShadow: 'rgb(172 172 172 / 17%) 0px 0.5px 1px 0px',
>     width: '100%',
>   }"
> ```
> 
> Let me know if this helps you.

Yes, I can confirm that  it works well in both Svelte and Vue when the attributes are applied this way.

**Comment by OvidijusParsiunas** [comment]
Good to hear, I will close this issue and if you have any other issues or suggestions for improvements please create a new issue. Thanks!
