### ISSUE TITLE
Cannot read properties of null (reading 'offsetWidth')

### ISSUE THREAD

**Issue by YodaLightsabr** [OvidijusParsiunas/active-table#16]
I'm implementing a data table with Active Table in my Next.js project, and I've started getting an error whenever trying to resize the width of my page.

```
Unhandled Runtime Error
TypeError: Cannot read properties of null (reading 'offsetWidth')

Call Stack
ParentResize.shouldRerenderTable
node_modules/active-table/dist/utils/render/parentResize.js (19:0)
ActiveTable.resizeCallback
node_modules/active-table/dist/utils/render/parentResize.js (25:0)
```

I've never used Lit before, but it seems like parentElement might not be defined on `at`.

**Comment by OvidijusParsiunas** [comment]
Hi @YodaLightsabr, is there any chance you can share what configuration you are using for the Active Table component implementation. Thanks!

**Comment by OvidijusParsiunas** [comment]
I am attempting to replicate the problem on my end, but it seems to work ok.

Would there be any chance that you could FORK the [live example](https://codesandbox.io/p/sandbox/deep-chat-nextjs-9pv25f?file=%2Fpackage.json%3A6%2C19&selection=%5B%7B%22endColumn%22%3A30%2C%22endLineNumber%22%3A28%2C%22startColumn%22%3A30%2C%22startLineNumber%22%3A28%7D%5D) and attempt to recreate the issue there, just so I can immediately analyze it and implement the fix. Thanks

**Comment by OvidijusParsiunas** [comment]
Hi, it's been a week with no response from OP. I will close this issue but feel free to reopen it if you can provide more details. Thankyou!

**Comment by YodaLightsabr** [comment]
Hi! Sorry I've missed your comments; I'll take a look at what you've sent and try to reproduce it from that.

**Comment by eviltik** [comment]
Same thing here, trying to use activetable in a lit-element component

https://codepen.io/franck34/pen/jOjzRmW

This is critical

**Comment by eviltik** [comment]
Show stopper spotted, please fix this

**Comment by OvidijusParsiunas** [comment]
This has been fixed in `active-table` and `active-table-react` version `1.1.6`. Big thankyout to @irshadmb for providing the code for the fix!
