### ISSUE TITLE
Is it possible to translate the table elements?

### ISSUE THREAD

**Issue by dmiric** [OvidijusParsiunas/active-table#24]
I would like to translate elements of the table like +New, Delete and such. Is that possible?

**Comment by OvidijusParsiunas** [comment]
Currently there is no API for changing the table options' text. However if you want to change it, I would recommend cloning/forking the project and customizing it to your preference. Running this component is very easy and the steps are described [here](https://github.com/OvidijusParsiunas/active-table/tree/main/component#construction_worker-local-setup).

The `+ New` text can be found in [this line](https://github.com/OvidijusParsiunas/active-table/blob/2e69b17fb00e898512d96ac081d4bbb0fcc85d37/component/src/elements/table/addNewElements/row/addNewRowElement.ts#L25).

The `Delete` text for the column dropdown menu can be found in [this line](https://github.com/OvidijusParsiunas/active-table/blob/2e69b17fb00e898512d96ac081d4bbb0fcc85d37/component/src/elements/dropdown/columnDropdown/columnDropdownButtonItemConf.ts#L53) and the `Delete` text for the row dropdown menu can be found [here](https://github.com/OvidijusParsiunas/active-table/blob/2e69b17fb00e898512d96ac081d4bbb0fcc85d37/component/src/elements/dropdown/rowDropdown/rowDropdownButtonItemConf.ts#L38).

**Comment by OvidijusParsiunas** [comment]
I will be closing this issue for now as it will not be pursued in the near future, however I will open it up if I'll work on it.

If you need any further assistance in this matter let me know. Thanks!
