### ISSUE TITLE
any interface to change ui label in another language

### ISSUE THREAD

**Issue by zkcode** [OvidijusParsiunas/active-table#26]
actually, this is a request instead of issue, Active-Table is a pretty good and stable enough table implementation. I love it

**Comment by OvidijusParsiunas** [comment]
Hi @zkcode. Thankyou for the kind words, could you elaborate what you mean by _ui label_?

**Comment by OvidijusParsiunas** [comment]
Hey @zkcode. Glad to hear you were able to get it working. I will be closing this issue now.
