### ISSUE TITLE
Cannot find module error while compiling

### ISSUE THREAD

**Issue by emirhanwsd** [OvidijusParsiunas/active-table#31]
Hello, I encountered a problem while compiling my project. I don't know if it's because of me.

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/vercel/path0/node_modules/active-table/dist/utils/outerTableComponents/pagination/paginationInternalUtils' imported from /vercel/path0/node_modules/active-table/dist/activeTable.js
--
04:57:24.692 | at new NodeError (node:internal/errors:405:5)
04:57:24.692 | at finalizeResolution (node:internal/modules/esm/resolve:327:11)
04:57:24.692 | at moduleResolve (node:internal/modules/esm/resolve:946:10)
04:57:24.693 | at defaultResolve (node:internal/modules/esm/resolve:1132:11)
04:57:24.693 | at nextResolve (node:internal/modules/esm/loader:163:28)
04:57:24.693 | at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
04:57:24.693 | at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
04:57:24.693 | at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
04:57:24.694 | at link (node:internal/modules/esm/module_job:76:36) {
04:57:24.694 | code: 'ERR_MODULE_NOT_FOUND'
```

**Comment by OvidijusParsiunas** [comment]
Hi @emirhanwsd. Could you tell me what the framework is that you are using and potentially share the code of how you are importing Active Table. Thankyou!

**Comment by emirhanwsd** [comment]
Hi @OvidijusParsiunas. I use Next.js as a framework.

There is how I import the Active Table.

![image](https://github.com/OvidijusParsiunas/active-table/assets/30156531/d3ee7c74-f1af-4406-9d7c-86975add187f)

There is how I use the Active Table.

![image](https://github.com/OvidijusParsiunas/active-table/assets/30156531/390e9374-5cb5-4df6-a8c2-830c9cfadb4b)

And, `package.json`.

![image](https://github.com/OvidijusParsiunas/active-table/assets/30156531/f68e7404-a13e-4290-8c9a-d7601455d7aa)

**Comment by emirhanwsd** [comment]
Any changes? @OvidijusParsiunas

**Comment by OvidijusParsiunas** [comment]
Hi @emirhanwsd. Sorry your comment above didn't load for me earlier for some reason.

Having looked at your code, the change that you need to make is to _dynamically_ import the package. The reason for this is because Active Table relies on browser APIs that are not available during SSR. Hence, the package needs to be loaded exclusively in the browser.

The change is very simple, all you need to do is to change the following:
```
import { ActiveTable } from "active-table-react"
```
to
```
export default function NameOfYourComponent() {
  const ActiveTable = dynamic(
    () => import('active-table-react').then((mod) => mod.ActiveTable),
    {
      ssr: false,
    }
  );
  ...
```

Here is a [live example](https://stackblitz.com/edit/active-table-nextjs?file=pages%2Findex.tsx)

**Comment by emirhanwsd** [comment]
Hello @OvidijusParsiunas. Thanks for your help. It worked.

**Comment by kpotter-m2** [comment]
> ```javascript
> export default function NameOfYourComponent() {
>    const ActiveTable = dynamic(
>      () => import('active-table-react').then((mod) => mod.ActiveTable),
>      {
>        ssr: false,
>      }
>    );
> ```

In case it helps someone else in the future, this was critical to resolve my issue, but the error maniffested as the following:

```bash
[0]  ⨯ node_modules/active-table/dist/utils/browser/browser.js (14:21) @ navigator
[0]  ⨯ ReferenceError: navigator is not defined
```

great work @OvidijusParsiunas !
