### ISSUE TITLE
how to sponsor

### ISSUE THREAD

**Issue by rsgilbert** [OvidijusParsiunas/active-table#32]
Hello guys,

I love your product!

This is good work. Really good work.

I've been searching for this exact thing for over 3 years.

Please tell me how I can sponsor.

**Comment by OvidijusParsiunas** [comment]
Hi @rsgilbert. Thankyou for your interest in sponsoring the project.
Currently, the only option to support it is via _Sponsor_ button on the right hand side of the repository.

<img width="1420" alt="Screenshot 2024-02-11 at 17 01 01" src="https://github.com/OvidijusParsiunas/active-table/assets/18709577/f94f837c-a912-406c-a4e0-476670513a9a">

Nevertheless, this is optional and best way to support the project is to use it. 😉 
Thankyou again!

**Comment by OvidijusParsiunas** [comment]
Update for future readers, you can now use [Polar](https://polar.sh/OvidijusParsiunas) to sponsor the project.

<img width="327" alt="image" src="https://github.com/OvidijusParsiunas/active-table/assets/18709577/223c412c-560c-4adc-9ca2-6e5126726082">
