### ISSUE TITLE
Modify exported CSV file name and maintain/keep rows on import

### ISSUE THREAD

**Issue by sbachiller** [OvidijusParsiunas/active-table#4]
Hello there,

I'm currently using your library on Angular, and I'm encountering a couple of issues with the CSV export and import functionality.

Firstly, the exported CSV files are always named "table_data.csv" and there seems to be no way to modify the file name. Could you please consider adding an option to change the file name during export?

Secondly, when I import a CSV file, the headers are not maintained. Additionally, the documentation states that the importCSV function returns a ColumnsDetails object, but it does not seem to return anything at all. Is there a way to intercept the end of the import process so that I can modify the data to add my headers?

I appreciate your hard work on this library, and I would be grateful if you could please look into these issues and provide any guidance or assistance. Thank you very much!

Best regards,

**Comment by OvidijusParsiunas** [comment]
Hi @sbachiller, thankyou very much for raising the issue.

For the first issue, I can definitely add a property that would allow you to specify what the output file name should be.

For the second issue, could you elaborate on what you mean by the headers not being maintained when you import a csv? I also did some investigation and found that the () => ColumnsDetails type for [importCSV](https://activetable.io/docs/methods#importCSV) in the documentation is INCORRECT and the function is not supposed to return anything. May I ask a little bit more about your usecase to see if I can provide guidance on how you can achieve what you want using the existing API or if I need to add something to the code. Thanks!

**Comment by OvidijusParsiunas** [comment]
In the meanwhile I am going to start working on the first issue and keep you updated on its progress.

**Comment by OvidijusParsiunas** [comment]
I have just published version 0.0217 for the [active-table](https://www.npmjs.com/package/active-table) npm package where you can specify the exported file's name when calling the `exportCSV` method. E.g:

`tableRef.exportCSV("customName");` or `tableRef.exportCSV("customName.csv")`.

If you are using the [csvButtons](https://activetable.io/docs/CSV#csvButtons) property to export your file via prebuilt buttons - you can specify the file name as follows (this is a JavaScript example and you can tailor it your [framework](https://activetable.io/examples/frameworks) as needed):

`<active-table csvButtons='{"export": {"fileName": "customName"}}'></active-table>`

You should see documentation updates for this shortly.

**Comment by sbachiller** [comment]
Hello!

Thank you very much for the quick update of the library. What I mean in the second item is that currently the first row of the content is used as the header of the table, and when you import a file the headers are overwritten as well. In my case, I would like to keep fixed headers for the user to enter only the data, so that when importing, only the file with content has to be added, as the headers already exist.

Also, I propose that when importing from a file there is the option to overwrite all the content or add it at the end, what do you think? :)

Again, thank you very much

Translated with www.DeepL.com/Translator (free version)

**Comment by OvidijusParsiunas** [comment]
I think I understand, what you want is to configure what is overwritten.

I can investigate the creation of the following options:

- overwrite all content (default)
- overwrite data only
- append data only

The risk for the last two is that the user may change the headers or create/remove columns so the imported CSV's data may no longer adhere to the correct columns. When using these options we need to trust the developer to configure the table properties to not allow the header to be changed with the use of `isHeaderTextEditable` and others.

Such implementation will take a little more time given how different people may configure the active table table as I need to make sure this feature will work correctly for all cases. As I am working on multiple projects, I can likely have a working prototype of this by tomorrow (similar time), but I will keep you posted on any progress.

Let me know what you think about these options.

**Comment by OvidijusParsiunas** [comment]
Hi, just an update, I am working on this and am currently ironing out a variety of edge cases that can cause errors. I will update this very shortly on how to use the new API.

**Comment by OvidijusParsiunas** [comment]
I have released the new functionality on package version 0.0.220. I am going to update the documentation for it tomorrow as it needs to be done in an easily understandable manner.

Here is how to use it:
When passing the options object inside the `importCSV` method or when using the `import` property in `csvButtons`, you can now add an additional property called `overwriteOptions`. This property is an object that has the following type: 

`{tableStartRow?: number; csvStartRow?: number}`

Both of these properties use zero index based numbers (they start with 0).

`tableStartRow` is the starting row at where you want the imported data to start overwriting the table rows. So if you don't want to overwrite the header and start from the second row, set it to `1`. The default value for this is `0` - meaning that the imported data will start overwriting at the start. You can additionally set this value to `-1` which will append the data after the last row of the table. 

`csvStartRow` is the starting row for the imported CSV data. So if you want to ignore the header, set it to `1`.

Here is an example on how to use it with the `importCSV` method:

`tableRef.importCSV({csvStartRow: 1, tableStartRow: 1});`

Here is an example on how to use it with `csvButtons` property:

`csvButtons='{"import": {"overwriteOptions": {"csvStartRow": 1, "tableStartRow": 1} } }'`

Let me know if you have any questions or encounter any issues. Thankyou!

**Comment by sbachiller** [comment]
Hi!
Thank you so much for implementing the features that I requested. I really appreciate your quick and efficient work. You have done a great job and I'm very happy with the result.

**Comment by sbachiller** [comment]
Hello again!

I am trying this new functionality and I think I found a bug while importing; seems like the last column of the file is missing on the table. I have been debugging the module and find out this is happening in insertMatrix.js:118 as I have isInsertRightAvailable on my table turned off. This makes indexOfNoRightInsertionColumn become -1 and slice the last value for each row. 

Changing isInsertRightAvailable to true makes it work, but I don't want the user to be able to add columns :(

Thanks in advance :)

**Comment by OvidijusParsiunas** [comment]
Hi @sbachiller, thanks for raising this issue! I think I can replicate this problem, but I want to make sure I found the same bug as you. Could you share the code you are using to configure the table? (No need to share any of your data, just the table configuration)

**Comment by OvidijusParsiunas** [comment]
Allowing the user to toggle the column overwrite behaviour just causes more problems, I will let the import CSV functionality ignore the `isInsertRightAvailable` and overwrite the data as needed.

This is available in version 0.0.222 of the npm package. Please let me know if this fixes your problem :)

**Comment by sbachiller** [comment]
Seems like working now :) Thanks you again!

**Comment by OvidijusParsiunas** [comment]
Quick update. I have changed the `csvRowStartIndex` property to `importRowStartIndex` to decouple the functionality from the use of `csv` and allow it to be extended to different file formats in the future. This change will be present from npm version 0.0.225.

The documentation for this will also be updated very soon.
