### ISSUE TITLE
How to get inputted data

### ISSUE THREAD

**Issue by luckystar0506** [OvidijusParsiunas/active-table#50]
Hi, Thanks to share your active-table.
I going to use your component.
But I don't know how to get data from table when input the data.
If possible, please answer about it or attach it to the [active table docs](https://activetable.io/docs)
Best regards.

**Comment by OvidijusParsiunas** [comment]
Hi @luckystar0506.
You can get data from the table using the [`getData`](https://activetable.io/docs/methods#getData) method.

**Comment by OvidijusParsiunas** [comment]
Everything is documented in the official [docs](https://activetable.io/docs/). Please use the search function on the top right to assist you with the particular queries. There are also more examples on various designs in the [example designs](https://activetable.io/examples/design) section.
If the documentation doesn't contain something you need, then please comment below. Thankyou!

**Comment by luckystar0506** [comment]
Thanks.
I want to set type specific cell.
Here is the example.
![image](https://github.com/OvidijusParsiunas/active-table/assets/99123221/e8102bfb-bca6-4ab3-82d2-3a950f794e1a)
How to set type for this?
Best regards.

**Comment by luckystar0506** [comment]
And does this component have merged cell feature?
![image](https://github.com/OvidijusParsiunas/active-table/assets/99123221/4957170f-99c9-4fc3-8426-fec1ebb46f42)

**Comment by OvidijusParsiunas** [comment]
Unfortunately cell based types and merged cells are not supported by Active Table. Sincere apologies.
