### ISSUE TITLE
SvelteKit - Unable to set availableDefaultColumnTypes={['Number']}

### ISSUE THREAD

**Issue by MateoAtwi** [OvidijusParsiunas/active-table#54]
I am able to generate a table properly in SvelteKit using the data variable; however, when I go to set some of the column settings it doesn't work. Am I formatting something incorrectly? I've tried a few different ways.

`<active-table
	availableDefaultColumnTypes={['Number']}
	headerStyles={{ default: { backgroundColor: '#d6d6d630' } }.toString()}
	displayAddNewColumn="false"
	defaultText="-"
	{data}
/>`

**Comment by MateoAtwi** [comment]
Solution was to stringify the input:

`availableDefaultColumnTypes={JSON.stringify(['Number'])}`

**Comment by OvidijusParsiunas** [comment]
For Svelte version 4.2.1 or lower - camel cased property names need to be stringified.

Please see the [live example for Svelte](https://stackblitz.com/edit/vitejs-vite-cm6j23?file=src%2FApp.svelte) and the [live example for SvelteKit](https://codesandbox.io/p/devbox/active-table-sveltekit-forked-fy9wlf?file=%2Fsrc%2Froutes%2F%2Bpage.svelte%3A31%2C29-31%2C34) to help you out.

Thankyou!
