### ISSUE TITLE
Event for table render

### ISSUE THREAD

**Issue by isgonfer83** [OvidijusParsiunas/active-table#7]
Similar to the rest of events (onCellUpdate, onContentUpdate, etc.) it would be a very nice enhancement to have an event which would fire once the table is finally rendered and visible to the user.

Thank you for your work.

**Comment by OvidijusParsiunas** [comment]
Hi @isgonfer83, thankyou for raising the issue!

The first time the `onContentUpdate` event is fired is technically when the table has been rendered so you could use this as an indicator on your app to monitor its loadtime.

If this does not meet your usecase, you could you provide a little bit more context so I could understand it better? Thanks!

**Comment by OvidijusParsiunas** [comment]
I will be working on fully supporting this feature now :)

**Comment by OvidijusParsiunas** [comment]
This feature is supported from component version 0.3.8. Please read [here](https://activetable.io/docs/filter) for more information.
